export const COLUMN_RESIZE = 'COLUMN_RESIZE';
export const ROW_RESIZE = 'ROW_RESIZE';
export const CHANGE_DATA_CELL = 'CHANGE_DATA_CELL';
export const CHANGE_STYLES_CELL = 'CHANGE_STYLES_CELL';
export const CHANGE_STYLE_CURRENT_CELL = 'CHANGE_STYLE_CURRENT_CELL';
export const CHANGE_TABLE_NAME = 'CHANGE_TABLE_NAME';
export const CHANGE_LAST_MODIFIED_DATE = 'CHANGE_LAST_MODIFIED_DATE';
